# 에러/예외 처리(Error/ Exception Handling)

## 디버깅

### 체크 사항

- branches: 모든 조건을 커버했는지?
- for loops: 반복문에 진입하는지, 원하는 횟수만큼 실행되는지
- while loops: for와 동일, 종료조건이 제대로 동작하는지
- function: 함수 호출 시, 함수 파라미터, 함수 결과 

### 디버깅 도구

- print 문: 특정 결과를 나눠서 출력하면서 생각
- 개발환경(text editor, IDE 등) 에서 제공하는 기능 활용
- Python tutor 활용: 단순 코드인 경우
- 뇌컴파일, 눈디버깅 *ㅋㅋㅋ...*

## 에러와 예외

### 문법 에러(Syntax error)

- 에러 발생 시 실행되지 않음
- 문제가 발생한 위치를 알려줌
- EOL: End of Line
- EOF: End of File

### 예외(Exception)

- 예상치 못한 상황(문장, 표현식이 올바르더라도 발생)을 맞이하면 실행을 멈춤
- 커스텀 에러를 만들어 관리가 가능
- `ZeroDivisionError: 0으로 나누고자 할 떄 발생`
- `NameError: namespace 상에 이름이 없는 경우`
- `TypeError: 타입 불일치`
- `ValueError: 타입은 올바르나 값이 적절하지 않은 경우 혹은 없는 경우`
- `IndexError: 인덱스가 존재하지 않거나 범위를 벗어나는 경우`
- `KeyError: 해당 키가 존재하지 않는 경우`
- `ModuleNotFoundError: 존재하지 않는 모듈을 import하는 경우`
- `ImportError: 모듈은 있으나 존재하지 않는 클래스/함수를 가져오는 경우`
- `KeyboardInterrupt: 임의로 프로그램을 종료한 경우`
- `IndentationError: Indentation이 적절하지 않는 경우`

## 예외 처리

- try 문(statement) / except 절(clause)을 이용하여 예외 처리가 가능함
- try문에서 예외가 발생하면 except 절이 실행되어 적절한 조치를 취함
- `try - 코드 실행`
- `except - 예외 발생 시 실행`
- `else - 예외 발생 안할 시 실행`
- `finally - 예외 발생 여부와 관계없이 항상 실행`

예시)

```python
try:
    num = input('100을 나눌 값을 입력하시오: ')
    ans = 100/int(num)
except ValueError:
    print('다시 입력하시오.')   
# 숫자입력: a
# 다시 입력하시오.
# 끝
except ZeroDivisionError as err:
    print(f'다시 입력하라고. {err}')
# 숫자입력: 0
# 다시 입력하라고. division by zero
# 끝
except:
    print('무슨 에러인 지 잘 모르겠어요.')
# 숫자입력: ctrl + c
# 무슨 에러인 지 잘 모르겠어요.
# 끝
else:
    print(ans)
    print('축하합니다.')
# 숫자입력: 1
# 100.0
# 축하합니다.
# 끝
finally:
    print('끝')
```

## 예외 발생시키기

- raise를 통해 예외를 강제로 발생

  `raise <표현식>(메세지)`

  `raise ValueError('값 에러 발생')`

  ```python
  def avg(scores):
  # 이곳에 코드를 작성하세요.
      try:
          return sum(scores) / len(scores)
          
      except ZeroDivisionError:
          raise ValueError(f'인자의 길이가 0입니다. 길이가 0이 아닌 인자를 입력하세요.')
  
      except TypeError:
          raise TypeError(f'인자는 list, tuple, range, set 의 자료형이어야 합니다.')
      
  avg([1, 2, 3])
  avg(123)
  ```

  

- assert를 통해 예외를 강제로 발생

  `assert <표현식>, <메시지>`

  `assert len([1, 2]) == 1, '길이가 1이 아닙니다.'`

